(function(){
  const U=window.FCU,S=window.FCState,I=window.FCIcon;
  let deferredPrompt=null,timerState={seconds:0,running:false,interval:null};
  const $=s=>document.querySelector(s), esc=U.escape;

  function navItem(path,label,icon,route){const active=route===path||(path!=='/'&&route.startsWith(path));return `<a href="#${path}" class="nav-item ${active?'active':''}">${I(icon)}<span>${label}</span>${active?'<span class="nav-trailing">●</span>':''}</a>`}
  function mobileItem(path,label,icon,route){const active=route===path||(path!=='/'&&route.startsWith(path));return `<a href="#${path}" class="${active?'active':''}">${I(icon,21)}<span>${label}</span></a>`}
  function shell(content,route,title='FitnessCut'){
    const st=S.get();
    return `<div class="shell">
      <aside class="sidebar">
        <a href="#/" class="brand"><span class="brand-mark">FC</span><div><b>FitnessCut</b><small>80 → 68 KG</small></div></a>
        <div class="nav-group-title">اصلی</div>
        <nav class="side-nav">
          ${navItem('/','خانه','home',route)}
          ${navItem('/training/push','PUSH','dumbbell',route)}
          ${navItem('/training/pull','PULL','dumbbell',route)}
          ${navItem('/training/legs','LEGS','dumbbell',route)}
        </nav>
        <div class="nav-group-title">برنامه و داده</div>
        <nav class="side-nav">
          ${navItem('/nutrition','تغذیه','food',route)}
          ${navItem('/supplements','مکمل‌ها','supplement',route)}
          ${navItem('/progress','پیشرفت','chart',route)}
          ${navItem('/settings','تنظیمات','settings',route)}
        </nav>
        <div class="side-note"><span>برنامه شخصی کات</span><b>۳ روز PPL</b><small>فعالیت روزانه پایین · داده‌ها روی دستگاه</small></div>
      </aside>
      <main class="main">
        <header class="topbar">
          <div class="topbar-title"><span class="eyebrow">FITNESS / CUT · 2026</span><b>${esc(title)}</b></div>
          <div class="topbar-actions"><button class="icon-btn ${st.editMode?'active':''}" data-action="toggle-edit" title="ویرایش برنامه">${I('edit')}</button><button class="icon-btn" data-action="toggle-theme" title="تغییر تم">${I(st.theme==='dark'?'sun':'moon')}</button></div>
        </header>
        <div class="content"><div class="page-enter">${content}</div></div>
        <nav class="mobile-nav">
          ${mobileItem('/','خانه','home',route)}
          ${mobileItem('/training','تمرین','dumbbell',route)}
          ${mobileItem('/nutrition','تغذیه','food',route)}
          ${mobileItem('/progress','پیشرفت','chart',route)}
          ${mobileItem('/settings','تنظیمات','settings',route)}
        </nav>
      </main>
    </div>`
  }
  function pageHead(title,subtitle,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${subtitle||''}</p></div><div class="page-actions">${actions}</div></div>`}
  function statCard(label,value,sub,icon,p){return `<article class="card stat"><div><div class="stat-head"><span>${label}</span><span class="stat-icon">${I(icon,18)}</span></div><div class="stat-value">${value}</div><div class="stat-sub">${sub||''}</div></div><div class="progress"><i style="width:${U.clamp(p||0,0,100)}%"></i></div></article>`}
  function weightChart(entries,target=68){const data=[...(entries||[])].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14);if(!data.length)return '<div class="empty">هنوز داده‌ای ثبت نشده است.</div>';const vals=data.map(x=>+x.weightKg),max=Math.max(...vals,target)+1,min=Math.min(...vals,target)-1,W=720,H=180,p=18,span=Math.max(1,max-min);const pts=data.map((d,i)=>({x:p+(i*(W-p*2))/Math.max(1,data.length-1),y:p+((max-d.weightKg)/span)*(H-p*2)}));const path=pts.map((q,i)=>`${i?'L':'M'}${q.x},${q.y}`).join(' '),area=`${path} L${pts.at(-1).x},${H-p} L${pts[0].x},${H-p} Z`,ty=p+((max-target)/span)*(H-p*2);return `<div class="mini-chart"><svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#26b98b" stop-opacity=".35"/><stop offset="1" stop-color="#26b98b" stop-opacity="0"/></linearGradient></defs><g class="chart-grid"><line x1="${p}" y1="${H*.35}" x2="${W-p}" y2="${H*.35}"/><line x1="${p}" y1="${H*.67}" x2="${W-p}" y2="${H*.67}"/><line x1="${p}" y1="${ty}" x2="${W-p}" y2="${ty}" stroke-dasharray="5 5"/></g><path class="chart-area" d="${area}"/><path class="chart-line" d="${path}"/>${pts.map(q=>`<circle class="chart-dot" cx="${q.x}" cy="${q.y}" r="4"/>`).join('')}</svg></div>`}

  function dashboard(){
    const st=S.get(),p=st.program.profile,macros=U.dailyMacros(st.program.meals),wid=U.suggestedWorkout(),w=st.program.workouts[wid],doneMeals=st.program.meals.filter(m=>st.daily.mealDone[m.id]),cons=U.dailyMacros(doneMeals),progress=U.weightProgress(p.startWeightKg,p.currentWeightKg,p.targetWeightKg),avg=U.movingAverage7(st.weights)||p.currentWeightKg;
    return `${pageHead('داشبورد','نمای سریع امروز، تمرین بعدی و روند کات')}
      <section class="card hero"><img class="hero-athlete" src="assets/hero-athlete.jpg" alt=""><div class="hero-copy"><span class="hero-kicker">PERSONAL CUT PROGRAM</span><h1>80 → 68 KG</h1><p>تمرکز روی کاهش چربی، حفظ عضله و قدرت. برنامه، لاگ تمرین و تنظیمات بدون حساب کاربری روی همین دستگاه ذخیره می‌شوند.</p><div class="hero-route"><strong>80</strong><div class="route-line"><i style="width:${progress}%"></i></div><strong>68</strong><div class="ring" style="--p:${progress}"><b>${U.fa(progress)}%</b></div></div></div></section>
      <div class="grid-4 section">
        ${statCard('کالری امروز',`${U.fa(cons.calories)} / ${U.fa(p.calorieTarget)}`,'بر اساس وعده‌های ثبت‌شده','fire',U.pct(cons.calories,p.calorieTarget))}
        ${statCard('پروتئین',`${U.fa(cons.protein,1)} / ${U.fa(p.proteinTarget)} g`,`برنامه کامل ≈ ${U.fa(macros.protein,1)}g`,'target',U.pct(cons.protein,p.proteinTarget))}
        ${statCard('قدم‌ها',`${U.fa(st.daily.steps)} / ${U.fa(p.stepTarget)}`,'برای جبران فعالیت شغلی پایین','steps',U.pct(st.daily.steps,p.stepTarget))}
        ${statCard('آب',`${U.fa(st.daily.waterMl/1000,1)} / ${U.fa(p.waterTargetMl/1000,1)} L`,'هدف روزانه','water',U.pct(st.daily.waterMl,p.waterTargetMl))}
      </div>
      <div class="dashboard-main">
        <article class="card today"><div class="today-copy"><span class="eyebrow">WORKOUT OF THE DAY</span><h2>امروز · ${w.title}</h2><p style="color:var(--muted)">${w.subtitle}</p><div class="metrics"><span class="metric-pill"><b>${U.fa(w.exercises.length)}</b> حرکت اصلی</span><span class="metric-pill"><b>Core</b> شکم و پهلو</span><span class="metric-pill"><b>${U.fa(w.cardio.durationMin)}–${U.fa(w.cardio.durationMax)}</b> دقیقه هوازی</span></div><a class="btn primary" style="margin-top:16px;width:fit-content" href="#/training/${wid}">${I('play',17)} شروع تمرین</a></div><img class="today-img" src="${w.exercises[0].image||'assets/hero-athlete.jpg'}" alt=""></article>
        <article class="card"><div style="display:flex;justify-content:space-between;align-items:center"><div><span class="eyebrow">WEIGHT TREND</span><h3 style="margin:3px 0">روند وزن</h3></div><b style="font-size:24px">${U.fa(p.currentWeightKg,1)} kg</b></div>${weightChart(st.weights,p.targetWeightKg)}<div class="metrics"><span class="metric-pill"><b>${U.fa(avg,1)}</b> میانگین ۷ روزه</span><span class="metric-pill"><b>${U.fa(Math.max(0,p.startWeightKg-p.currentWeightKg),1)}</b> کاهش کل</span><span class="metric-pill"><b>${U.fa(Math.max(0,p.currentWeightKg-p.targetWeightKg),1)}</b> باقی‌مانده</span></div></article>
      </div>
      <div class="section-title"><div><h2>ثبت سریع امروز</h2><span>قدم و آب بدون خروج از داشبورد</span></div></div>
      <div class="grid-2"><article class="card"><div class="stat-head"><span>قدم‌های امروز</span><span class="stat-icon">${I('steps',18)}</span></div><input class="input" data-action="quick-steps" type="number" inputmode="numeric" value="${st.daily.steps}"><div class="progress"><i style="width:${U.pct(st.daily.steps,p.stepTarget)}%"></i></div></article><article class="card"><div class="stat-head"><span>آب امروز</span><span class="stat-icon">${I('water',18)}</span></div><div class="metrics"><button class="btn sm" data-action="water-add" data-value="250">+۲۵۰ ml</button><button class="btn sm" data-action="water-add" data-value="500">+۵۰۰ ml</button><button class="btn sm" data-action="water-add" data-value="750">+۷۵۰ ml</button><button class="btn sm ghost" data-action="water-add" data-value="-250">−۲۵۰</button></div><div class="stat-value">${U.fa(st.daily.waterMl)} ml</div></article></div>`
  }

  function trainingOverview(){const ws=S.get().program.workouts;return `${pageHead('تمرین','سه روز Push / Pull / Legs با هوازی، شکم، کول و ساعد یکپارچه')}<div class="grid-3">${['push','pull','legs'].map(id=>{const w=ws[id];return `<a class="card" href="#/training/${id}" style="overflow:hidden;padding:0"><img src="${w.exercises[0].image}" style="width:100%;height:190px;object-fit:cover"><div style="padding:16px"><span class="eyebrow">${id.toUpperCase()}</span><h2 style="margin:2px 0">${w.title}</h2><p style="color:var(--muted);margin:0 0 10px">${w.subtitle}</p><div class="metrics"><span class="metric-pill">${w.duration}</span><span class="metric-pill">${w.cardio.durationMin}–${w.cardio.durationMax} دقیقه هوازی</span></div></div></a>`}).join('')}</div>`}

  function setRows(day,ex){const st=S.get(),logs=st.daily.workoutLogs?.[day]?.[ex.id]||[],prev=S.previousSets(day,ex.id);const rows=[];for(let i=0;i<ex.sets;i++){const l=logs[i]||{weightKg:null,reps:null,done:false},pr=prev[i];rows.push(`<div class="set-row"><div class="set-n">${U.fa(i+1)}</div><div class="previous">${pr?.weightKg??'—'} × ${pr?.reps??'—'}</div><input class="input" data-action="set-log" data-day="${day}" data-ex="${ex.id}" data-index="${i}" data-field="weightKg" type="number" inputmode="decimal" step=".5" value="${l.weightKg??''}" placeholder="kg"><input class="input" data-action="set-log" data-day="${day}" data-ex="${ex.id}" data-index="${i}" data-field="reps" type="number" inputmode="numeric" value="${l.reps??''}" placeholder="تکرار"><button class="set-ok ${l.done?'done':''}" data-action="set-done" data-day="${day}" data-ex="${ex.id}" data-index="${i}" data-rest="${ex.restSec}">${I('check',17)}</button></div>`)}const completed=logs.length>=ex.sets&&logs.slice(0,ex.sets).every(x=>x.done&&Number(x.reps)>=ex.repMax);return `<div class="set-area"><div class="set-head"><span>ست</span><span>قبلی</span><span>وزنه</span><span>تکرار</span><span></span></div>${rows.join('')}${completed?'<div class="overload">پیشنهاد جلسه بعد: اگر RIR هدف هم حفظ شده، وزنه را حدود ۲ تا ۵٪ افزایش بده.</div>':''}</div>`}
  function exerciseCard(day,ex,index,accessory=false){const st=S.get();return `<article class="card exercise"><div class="exercise-main">${ex.image?`<img class="exercise-photo" src="${ex.image}" alt="${esc(ex.nameFa)}">`:`<div class="exercise-photo" style="display:grid;place-items:center">${I('dumbbell',28)}</div>`}<div class="exercise-copy"><div style="display:flex;gap:7px;align-items:center"><span class="chip"><strong>${U.fa(index+1)}</strong></span>${accessory?'<span class="chip">تکمیلی</span>':''}${ex.optional?'<span class="chip">اختیاری</span>':''}</div><h3>${esc(ex.nameFa)}</h3><span class="en">${esc(ex.nameEn)}</span><div class="metrics"><span class="chip">${esc(ex.muscleGroup)}</span><span class="chip">${esc(ex.equipment)}</span></div><p>${esc(ex.instructions)}</p>${ex.replacementNote?`<p><b>${esc(ex.replacementNote)}</b></p>`:''}${st.editMode?`<div class="metrics"><button class="btn sm" data-action="edit-exercise" data-day="${day}" data-ex="${ex.id}">${I('edit',14)} ویرایش</button><button class="btn sm danger" data-action="remove-exercise" data-day="${day}" data-ex="${ex.id}">${I('trash',14)} حذف</button></div>`:''}</div><div class="exercise-side"><div class="exercise-meta"><span>ست</span><b>${U.fa(ex.sets)}</b></div><div class="exercise-meta"><span>تکرار</span><b>${U.fa(ex.repMin)}–${U.fa(ex.repMax)}</b></div><div class="exercise-meta"><span>استراحت</span><b>${U.fa(ex.restSec)} ث</b></div><div class="exercise-meta"><span>RIR</span><b>${U.fa(ex.rirMin)}–${U.fa(ex.rirMax)}</b></div></div></div>${setRows(day,ex)}</article>`}
  function workoutPage(day){const st=S.get(),w=st.program.workouts[day];if(!w)return trainingOverview();const actions=st.editMode?`<button class="btn" data-action="add-exercise" data-day="${day}">${I('plus',16)} افزودن حرکت</button><button class="btn" data-action="edit-cardio" data-day="${day}">${I('edit',16)} ویرایش هوازی</button>`:'';return `${pageHead(`تمرین ${w.title}`,w.subtitle,actions)}<div class="mobile-sheet-tabs"><a href="#/training/push" class="${day==='push'?'active':''}">PUSH</a><a href="#/training/pull" class="${day==='pull'?'active':''}">PULL</a><a href="#/training/legs" class="${day==='legs'?'active':''}">LEGS</a></div><article class="card workout-hero"><div><span class="eyebrow">${w.title} SESSION</span><h1>${w.title}</h1><div class="focuses">${w.focus.map(x=>`<span class="chip"><strong>${esc(x)}</strong></span>`).join('')}</div></div><div class="metrics"><span class="metric-pill"><b>${w.duration}</b> زمان</span><span class="metric-pill"><b>RIR 1–3</b> ست‌های اصلی</span></div></article>
      <div class="section-title"><div><h2>حرکات اصلی</h2><span>وزنه و تکرار واقعی هر ست را ثبت کن</span></div></div><div class="exercise-list">${w.exercises.map((ex,i)=>exerciseCard(day,ex,i)).join('')}</div>
      ${w.accessory.length?`<div class="section-title"><div><h2>${day==='pull'?'کول و ساعد':'ساعد و حرکات تکمیلی'}</h2><span>حجم کنترل‌شده، بدون شلوغ‌کردن برنامه</span></div></div><div class="exercise-list">${w.accessory.map((ex,i)=>exerciseCard(day,ex,i,true)).join('')}</div>`:''}
      <div class="section-title"><div><h2>شکم و پهلو</h2><span>ناحیه تمرکز تمرین؛ نه چربی‌سوزی موضعی</span></div></div><div class="core-grid">${w.core.map(c=>`<div class="core"><span class="core-region">${esc(c.region)}</span><h3>${esc(c.name)}</h3><p><b>${U.fa(c.sets)} ست × ${esc(c.reps)}</b></p><p>${esc(c.instructions)}</p></div>`).join('')}</div>
      <div class="section-title"><div><h2>هوازی و فعالیت روزانه</h2><span>متناسب با فعالیت شغلی پایین</span></div></div><article class="card cardio"><div><span class="eyebrow">CARDIO / DAILY ACTIVITY</span><h3>${esc(w.cardio.type)}</h3><p style="color:var(--muted)">${esc(w.cardio.description)}</p><div class="metrics"><span class="metric-pill"><b>${U.fa(w.cardio.durationMin)}–${U.fa(w.cardio.durationMax)}</b> دقیقه</span><span class="metric-pill"><b>${esc(w.cardio.intensity)}</b> شدت</span><span class="metric-pill"><b>${U.fa(w.cardio.stepTargetMin)}–${U.fa(w.cardio.stepTargetMax)}</b> قدم</span></div></div><div class="cardio-visual"><div style="text-align:center">${I('steps',28)}<b>${U.fa(w.cardio.durationMin)}–${U.fa(w.cardio.durationMax)}</b><small>MIN</small></div></div></article>
      <div class="section" style="display:flex;justify-content:flex-end"><button class="btn primary" data-action="finish-workout" data-day="${day}">${I('check',17)} پایان و ثبت جلسه</button></div>`}

  function nutrition(){const st=S.get(),p=st.program.profile,actual=U.dailyMacros(st.program.meals),actions=st.editMode?`<button class="btn" data-action="add-food" data-meal="breakfast">${I('plus',16)} خوراکی جدید</button>`:'';return `${pageHead('تغذیه','پنج وعده، محاسبه زنده ماکرو و واحد خانگی',actions)}<article class="card macro-summary"><div class="macro-ring"><div><b>${U.fa(actual.calories)}</b><span>kcal</span></div></div><div><div class="macro-pills"><div class="macro-pill"><b>${U.fa(actual.protein,1)}g</b><span>پروتئین · هدف ${U.fa(p.proteinTarget)}</span></div><div class="macro-pill"><b>${U.fa(actual.carbs,1)}g</b><span>کربوهیدرات · هدف ${U.fa(p.carbTarget)}</span></div><div class="macro-pill"><b>${U.fa(actual.fat,1)}g</b><span>چربی · هدف ${U.fa(p.fatTarget)}</span></div></div><div class="progress"><i style="width:${U.pct(actual.calories,p.calorieTarget)}%"></i></div><small style="color:var(--muted)">هدف کالری: ${U.fa(p.calorieTarget)} kcal · جمع فعلی از روی خوراکی‌های موجود محاسبه می‌شود.</small></div></article>
      <article class="card olive-toggle section"><div><h3 style="margin:0">تنظیم روغن زیتون / کربوهیدرات</h3><p style="margin:3px 0 0;color:var(--muted);font-size:11px">حالت ۱: روغن فقط ناهار و برنج بیشتر. حالت ۲: یک قاشق چای‌خوری دیگر در شام و برنج ناهار کمتر.</p></div><div class="segmented"><button class="${st.program.oliveOilMode===1?'active':''}" data-action="olive-mode" data-value="1">حالت ۱</button><button class="${st.program.oliveOilMode===2?'active':''}" data-action="olive-mode" data-value="2">حالت ۲</button></div></article>
      <div class="meal-list section">${st.program.meals.map(meal=>{const mm=U.mealMacros(meal),done=!!st.daily.mealDone[meal.id];return `<article class="card meal"><img class="meal-photo" src="${meal.image}" alt="${esc(meal.title)}"><div class="meal-body"><div class="meal-head"><div><h3>${esc(meal.title)}</h3><small>${esc(meal.time)}</small></div><button class="btn sm ${done?'primary':''}" data-action="meal-done" data-id="${meal.id}">${I('check',14)} ${done?'ثبت شد':'ثبت وعده'}</button></div><div class="meal-foods">${meal.foods.map(f=>`<div class="food-row"><div><div class="food-name">${esc(f.name)}</div><div class="food-house">${esc(f.household)}</div></div><div class="food-grams">${st.editMode?`<input class="input" style="min-height:32px;padding:4px 7px" type="number" data-action="food-grams" data-meal="${meal.id}" data-food="${f.id}" value="${f.grams}">`:`${U.fa(f.grams,1)} گرم`}</div><div class="food-house">${U.fa(f.macros.calories)} kcal · P ${U.fa(f.macros.protein,1)}</div>${st.editMode?`<div class="food-actions"><button class="btn sm" data-action="edit-food" data-meal="${meal.id}" data-food="${f.id}">${I('edit',13)}</button><button class="btn sm" data-action="duplicate-food" data-meal="${meal.id}" data-food="${f.id}">${I('copy',13)}</button><button class="btn sm danger" data-action="remove-food" data-meal="${meal.id}" data-food="${f.id}">${I('trash',13)}</button></div>`:'<span></span>'}</div>`).join('')}</div>${st.editMode?`<button class="btn sm" style="margin-top:8px" data-action="add-food" data-meal="${meal.id}">${I('plus',13)} افزودن خوراکی</button>`:''}</div><div class="meal-kcal"><b>${U.fa(mm.calories)}</b><span>kcal</span><small>P ${U.fa(mm.protein,1)} · C ${U.fa(mm.carbs,1)} · F ${U.fa(mm.fat,1)}</small></div></article>`}).join('')}</div>`}

  function supplements(){const st=S.get();return `${pageHead('مکمل‌ها','اولویت‌ها، دوز و ثبت مصرف روزانه')}<div class="supp-grid">${st.program.supplements.map(s=>{const done=!!st.daily.supplementDone[s.id],lab=s.priority==='high'?'اولویت بالا':s.priority==='medium'?'کاربردی':'اختیاری / پایین';return `<article class="card supp"><img src="${s.image}" alt="${esc(s.nameFa)}"><div class="supp-body"><div class="supp-head"><div><span class="en">${esc(s.nameEn)}</span><h3>${esc(s.nameFa)}</h3></div><span class="priority ${s.priority}">${lab}</span></div><div class="supp-lines"><p><b>مقدار:</b> ${esc(s.amount)}</p><p><b>زمان:</b> ${esc(s.timing)}</p><p><b>هدف:</b> ${esc(s.purpose)}</p>${s.note?`<p>${esc(s.note)}</p>`:''}</div><div class="metrics"><button class="btn sm ${done?'primary':''}" data-action="supp-done" data-id="${s.id}">${I('check',14)} ${done?'مصرف شد':'ثبت مصرف'}</button>${st.editMode?`<button class="btn sm" data-action="edit-supp" data-id="${s.id}">${I('edit',14)} ویرایش</button>`:''}</div></div></article>`}).join('')}</div><div class="section grid-2"><article class="card"><div class="stat-head"><span>آب روزانه</span><span class="stat-icon">${I('water',18)}</span></div><div class="stat-value">حداقل ۳ لیتر</div><div class="stat-sub">با توجه به تمرین، تعریق و شرایط روز قابل افزایش است.</div></article><article class="card"><div class="stat-head"><span>ریکاوری</span><span class="stat-icon">${I('timer',18)}</span></div><div class="stat-value">۷ تا ۸ ساعت خواب</div><div class="stat-sub">پایه اصلی حفظ عملکرد، ریکاوری و کنترل اشتها.</div></article></div>`}

  function progress(){const st=S.get(),p=st.program.profile,avg=U.movingAverage7(st.weights)||p.currentWeightKg;return `${pageHead('پیشرفت','وزن، دور کمر و میانگین هفت‌روزه')}<div class="grid-4">${statCard('وزن فعلی',`${U.fa(p.currentWeightKg,1)} kg`,'آخرین ثبت','target',U.weightProgress(p.startWeightKg,p.currentWeightKg,p.targetWeightKg))}${statCard('میانگین ۷ روزه',`${U.fa(avg,1)} kg`,'برای تصمیم‌گیری بهتر','chart',0)}${statCard('کاهش کل',`${U.fa(Math.max(0,p.startWeightKg-p.currentWeightKg),1)} kg`,'از شروع برنامه','fire',U.weightProgress(p.startWeightKg,p.currentWeightKg,p.targetWeightKg))}${statCard('باقی‌مانده',`${U.fa(Math.max(0,p.currentWeightKg-p.targetWeightKg),1)} kg`,'تا هدف ۶۸','steps',100-U.weightProgress(p.startWeightKg,p.currentWeightKg,p.targetWeightKg))}</div><div class="progress-layout section"><article class="card"><div class="section-title" style="margin-top:0"><div><h2>روند وزن</h2><span>آخرین ۱۴ ثبت</span></div></div>${weightChart(st.weights,p.targetWeightKg)}</article><article class="card"><h3 style="margin-top:0">ثبت جدید</h3><form class="form" id="weightForm"><div class="field"><label>تاریخ</label><input class="input" name="date" type="date" value="${U.today()}" required></div><div class="form-row"><div class="field"><label>وزن (kg)</label><input class="input" name="weight" type="number" step=".1" inputmode="decimal" required></div><div class="field"><label>دور کمر (cm)</label><input class="input" name="waist" type="number" step=".1" inputmode="decimal"></div></div><div class="field"><label>یادداشت</label><textarea class="input" name="note" rows="3"></textarea></div><button class="btn primary" type="submit">${I('save',16)} ثبت وزن</button></form></article></div><article class="card section"><h3 style="margin-top:0">تاریخچه</h3><div style="overflow:auto"><table class="table"><thead><tr><th>تاریخ</th><th>وزن</th><th>دور کمر</th><th>یادداشت</th><th></th></tr></thead><tbody>${[...st.weights].sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<tr><td>${esc(x.date)}</td><td>${U.fa(x.weightKg,1)} kg</td><td>${x.waistCm?U.fa(x.waistCm,1):'—'}</td><td>${esc(x.note||'')}</td><td>${x.id==='start'?'':`<button class="btn sm danger" data-action="remove-weight" data-id="${x.id}">${I('trash',13)}</button>`}</td></tr>`).join('')}</tbody></table></div></article>`}

  function settings(){const st=S.get(),p=st.program.profile;return `${pageHead('تنظیمات','پروفایل، اهداف، پشتیبان، چاپ و نصب')}<div class="settings-grid"><article class="card"><h3 style="margin-top:0">پروفایل و اهداف</h3><div class="setting-list">${settingNumber('سن','سال',p.age,'age')}${settingNumber('قد','سانتی‌متر',p.heightCm,'heightCm')}${settingNumber('وزن هدف','کیلوگرم',p.targetWeightKg,'targetWeightKg',.1)}${settingNumber('کالری هدف','kcal',p.calorieTarget,'calorieTarget')}${settingNumber('پروتئین هدف','گرم',p.proteinTarget,'proteinTarget')}${settingNumber('کربوهیدرات هدف','گرم',p.carbTarget,'carbTarget')}${settingNumber('چربی هدف','گرم',p.fatTarget,'fatTarget')}${settingNumber('قدم هدف','قدم',p.stepTarget,'stepTarget')}${settingNumber('آب هدف','ml',p.waterTargetMl,'waterTargetMl')}</div></article><article class="card"><h3 style="margin-top:0">ظاهر و مدیریت</h3><div class="setting-list"><div class="setting-row"><label>تم<strong>روشن، تاریک یا سیستم</strong></label><select class="input" data-action="theme-select"><option value="system" ${st.theme==='system'?'selected':''}>سیستم</option><option value="light" ${st.theme==='light'?'selected':''}>روشن</option><option value="dark" ${st.theme==='dark'?'selected':''}>تاریک</option></select></div><div class="setting-row"><label>حالت ویرایش<strong>تغییر داده‌ها از داخل اپ</strong></label><button class="btn ${st.editMode?'primary':''}" data-action="toggle-edit">${I('edit',15)} ${st.editMode?'فعال':'غیرفعال'}</button></div><button class="btn" data-action="export">${I('download',16)} خروجی پشتیبان JSON</button><button class="btn" data-action="import">${I('upload',16)} بازیابی پشتیبان</button><input id="importFile" type="file" accept="application/json" hidden><button class="btn" data-action="install">${I('download',16)} نصب Web App</button><button class="btn" data-action="print">${I('print',16)} چاپ برنامه A4</button><button class="btn danger" data-action="reset">${I('reset',16)} بازگشت به برنامه اصلی</button></div></article></div><div class="section-title"><div><h2>بررسی داده برنامه</h2><span>ناسازگاری‌ها به‌جای تغییر خاموش نمایش داده می‌شوند</span></div></div><div style="display:grid;gap:8px">${st.program.validationNotes.map(x=>`<div class="validation">${I('info',16)}<span>${esc(x)}</span></div>`).join('')}</div>`}
  function settingNumber(label,unit,val,key,step=1){return `<div class="setting-row"><label>${label}<strong>${unit}</strong></label><input class="input" data-action="profile-number" data-key="${key}" type="number" step="${step}" value="${val}"></div>`}

  function renderPrint(){const p=S.get().program,days=['push','pull','legs'];const mealSheets=`<section class="print-sheet"><div class="print-title"><h1>برنامه غذایی کات · FitnessCut</h1><p>۸۰ → ۶۸ کیلوگرم · هدف ${p.profile.calorieTarget} kcal</p></div>${p.meals.map(m=>`<div class="print-meal"><h3>${esc(m.title)} · ${U.fa(U.mealMacros(m).calories)} kcal</h3><ul>${m.foods.map(f=>`<li>${esc(f.name)}: ${esc(f.household)} · ${U.fa(f.grams,1)} گرم</li>`).join('')}</ul></div>`).join('')}<div class="print-footer">حالت روغن زیتون: ${p.oliveOilMode} · مقادیر تقریبی و قابل ویرایش‌اند.</div></section><section class="print-sheet"><div class="print-title"><h1>برنامه مکمل‌ها</h1><p>کراتین و وی اولویت بالاتر؛ BCAA و گلوتامین اختیاری.</p></div><div class="print-grid">${p.supplements.map(s=>`<div class="print-card"><h3>${esc(s.nameFa)}</h3><p><b>مقدار:</b> ${esc(s.amount)}</p><p><b>زمان:</b> ${esc(s.timing)}</p><p><b>هدف:</b> ${esc(s.purpose)}</p></div>`).join('')}</div></section>`;const work=days.map(d=>{const w=p.workouts[d];return `<section class="print-sheet"><div class="print-title"><h1>برنامه تمرین ${w.title}</h1><p>${esc(w.subtitle)} · ${esc(w.duration)}</p></div><div class="print-grid">${[...w.exercises,...w.accessory].map(ex=>`<div class="print-card"><h3>${esc(ex.nameFa)}</h3><p>${ex.sets} ست · ${ex.repMin} تا ${ex.repMax} تکرار · ${ex.restSec} ثانیه</p><p>${esc(ex.instructions)}</p></div>`).join('')}</div><h3>شکم و پهلو</h3><div class="print-grid">${w.core.map(c=>`<div class="print-card"><b>${esc(c.region)} · ${esc(c.name)}</b><p>${c.sets} ست × ${esc(c.reps)}</p></div>`).join('')}</div><h3>هوازی</h3><div class="print-card"><b>${esc(w.cardio.type)}</b><p>${w.cardio.durationMin} تا ${w.cardio.durationMax} دقیقه · ${esc(w.cardio.intensity)}</p><p>${esc(w.cardio.description)}</p></div></section>`}).join('');$('#printRoot').innerHTML=mealSheets+work}

  function render(){const route=U.route();let content,title;if(route==='/'){content=dashboard();title='خانه'}else if(route==='/training'||route==='/training/'){content=trainingOverview();title='تمرین'}else if(/^\/training\/(push|pull|legs)/.test(route)){const d=route.split('/')[2];content=workoutPage(d);title=`تمرین ${d.toUpperCase()}`}else if(route.startsWith('/nutrition')){content=nutrition();title='تغذیه'}else if(route.startsWith('/supplements')){content=supplements();title='مکمل‌ها'}else if(route.startsWith('/progress')){content=progress();title='پیشرفت'}else if(route.startsWith('/settings')){content=settings();title='تنظیمات'}else{content=dashboard();title='خانه'}$('#app').innerHTML=shell(content,route,title);renderPrint();bindForms();}

  function modal(title,body,footer=''){ $('#modalRoot').innerHTML=`<div class="modal-backdrop" data-action="modal-backdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="icon-btn" data-action="close-modal">${I('close',18)}</button></div>${body}${footer?`<div class="page-actions" style="margin-top:14px">${footer}</div>`:''}</div></div>` }
  function closeModal(){$('#modalRoot').innerHTML=''}
  let toastTimer;function toast(msg){clearTimeout(toastTimer);$('#toastRoot').innerHTML=`<div class="toast">${esc(msg)}</div>`;toastTimer=setTimeout(()=>$('#toastRoot').innerHTML='',2600)}
  function startTimer(sec){timerState.seconds=Number(sec)||90;timerState.running=true;clearInterval(timerState.interval);timerState.interval=setInterval(()=>{if(timerState.running&&timerState.seconds>0){timerState.seconds--;drawTimer()}else if(timerState.seconds<=0){timerState.running=false;drawTimer()}},1000);drawTimer()}
  function drawTimer(){const root=$('#timerRoot');root.innerHTML=`<div class="timer show">${I('timer',18)}<b>${U.time(timerState.seconds)}</b><div class="timer-actions"><button data-action="timer-toggle">${I(timerState.running?'pause':'play',16)}</button><button data-action="timer-add">+۳۰ ث</button><button data-action="timer-close">${I('close',16)}</button></div></div>`}
  function stopTimer(){clearInterval(timerState.interval);timerState={seconds:0,running:false,interval:null};$('#timerRoot').innerHTML=''}

  function editFoodModal(mealId,foodId){const st=S.get(),m=st.program.meals.find(x=>x.id===mealId),f=m?.foods.find(x=>x.id===foodId);if(!f)return;modal('ویرایش خوراکی',`<form id="foodEditForm" class="modal-grid"><input type="hidden" name="meal" value="${mealId}"><input type="hidden" name="food" value="${foodId}"><div class="field wide"><label>نام</label><input class="input" name="name" value="${esc(f.name)}"></div><div class="field"><label>گرم</label><input class="input" type="number" step=".1" name="grams" value="${f.grams}"></div><div class="field"><label>معادل خانگی</label><input class="input" name="household" value="${esc(f.household)}"></div><div class="field"><label>کالری</label><input class="input" type="number" step=".1" name="calories" value="${f.macros.calories}"></div><div class="field"><label>پروتئین</label><input class="input" type="number" step=".1" name="protein" value="${f.macros.protein}"></div><div class="field"><label>کربوهیدرات</label><input class="input" type="number" step=".1" name="carbs" value="${f.macros.carbs}"></div><div class="field"><label>چربی</label><input class="input" type="number" step=".1" name="fat" value="${f.macros.fat}"></div><div class="wide"><button class="btn primary" type="submit">ذخیره</button></div></form>`)}
  function editSuppModal(id){const s=S.get().program.supplements.find(x=>x.id===id);if(!s)return;modal('ویرایش مکمل',`<form id="suppEditForm" class="modal-grid"><input type="hidden" name="id" value="${id}"><div class="field"><label>نام فارسی</label><input class="input" name="nameFa" value="${esc(s.nameFa)}"></div><div class="field"><label>نام انگلیسی</label><input class="input" name="nameEn" value="${esc(s.nameEn)}"></div><div class="field wide"><label>مقدار</label><input class="input" name="amount" value="${esc(s.amount)}"></div><div class="field wide"><label>زمان</label><input class="input" name="timing" value="${esc(s.timing)}"></div><div class="field wide"><label>هدف</label><textarea class="input" name="purpose" rows="3">${esc(s.purpose)}</textarea></div><div class="field"><label>اولویت</label><select class="input" name="priority"><option value="high" ${s.priority==='high'?'selected':''}>بالا</option><option value="medium" ${s.priority==='medium'?'selected':''}>متوسط</option><option value="low" ${s.priority==='low'?'selected':''}>پایین</option></select></div><div><button class="btn primary" type="submit">ذخیره</button></div></form>`)}
  function editExerciseModal(day,id){const w=S.get().program.workouts[day],ex=[...w.exercises,...w.accessory].find(x=>x.id===id);if(!ex)return;modal('ویرایش حرکت',`<form id="exerciseEditForm" class="modal-grid"><input type="hidden" name="day" value="${day}"><input type="hidden" name="id" value="${id}"><div class="field"><label>نام فارسی</label><input class="input" name="nameFa" value="${esc(ex.nameFa)}"></div><div class="field"><label>نام انگلیسی</label><input class="input" name="nameEn" value="${esc(ex.nameEn)}"></div><div class="field"><label>گروه عضلانی</label><input class="input" name="muscleGroup" value="${esc(ex.muscleGroup)}"></div><div class="field"><label>تجهیزات</label><input class="input" name="equipment" value="${esc(ex.equipment)}"></div><div class="field"><label>ست</label><input class="input" type="number" name="sets" value="${ex.sets}"></div><div class="field"><label>حداقل تکرار</label><input class="input" type="number" name="repMin" value="${ex.repMin}"></div><div class="field"><label>حداکثر تکرار</label><input class="input" type="number" name="repMax" value="${ex.repMax}"></div><div class="field"><label>استراحت (ثانیه)</label><input class="input" type="number" name="restSec" value="${ex.restSec}"></div><div class="field"><label>RIR حداقل</label><input class="input" type="number" name="rirMin" value="${ex.rirMin}"></div><div class="field"><label>RIR حداکثر</label><input class="input" type="number" name="rirMax" value="${ex.rirMax}"></div><div class="field wide"><label>توضیح اجرا</label><textarea class="input" name="instructions" rows="4">${esc(ex.instructions)}</textarea></div><div class="wide"><button class="btn primary" type="submit">ذخیره</button></div></form>`)}
  function editCardioModal(day){const c=S.get().program.workouts[day].cardio;modal('ویرایش هوازی',`<form id="cardioEditForm" class="modal-grid"><input type="hidden" name="day" value="${day}"><div class="field wide"><label>نوع هوازی</label><input class="input" name="type" value="${esc(c.type)}"></div><div class="field"><label>حداقل دقیقه</label><input class="input" type="number" name="durationMin" value="${c.durationMin}"></div><div class="field"><label>حداکثر دقیقه</label><input class="input" type="number" name="durationMax" value="${c.durationMax}"></div><div class="field"><label>شدت</label><input class="input" name="intensity" value="${esc(c.intensity)}"></div><div class="field"><label>قدم حداقل</label><input class="input" type="number" name="stepTargetMin" value="${c.stepTargetMin}"></div><div class="field"><label>قدم حداکثر</label><input class="input" type="number" name="stepTargetMax" value="${c.stepTargetMax}"></div><div class="field wide"><label>توضیح</label><textarea class="input" name="description" rows="4">${esc(c.description)}</textarea></div><div class="wide"><button class="btn primary" type="submit">ذخیره</button></div></form>`)}

  function bindForms(){const wf=$('#weightForm');if(wf)wf.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(wf);S.addWeight({date:d.get('date'),weightKg:Number(d.get('weight')),waistCm:d.get('waist')?Number(d.get('waist')):undefined,note:String(d.get('note')||'')});toast('وزن ثبت شد.')})}
  document.addEventListener('submit',e=>{const f=e.target;if(f.id==='foodEditForm'){e.preventDefault();const d=new FormData(f);S.updateFood(d.get('meal'),d.get('food'),{name:String(d.get('name')),grams:Number(d.get('grams')),household:String(d.get('household')),macros:{calories:Number(d.get('calories')),protein:Number(d.get('protein')),carbs:Number(d.get('carbs')),fat:Number(d.get('fat'))}});closeModal();toast('خوراکی به‌روز شد.')}if(f.id==='suppEditForm'){e.preventDefault();const d=new FormData(f);S.updateSupplement(d.get('id'),{nameFa:String(d.get('nameFa')),nameEn:String(d.get('nameEn')),amount:String(d.get('amount')),timing:String(d.get('timing')),purpose:String(d.get('purpose')),priority:String(d.get('priority'))});closeModal();toast('مکمل به‌روز شد.')}if(f.id==='exerciseEditForm'){e.preventDefault();const d=new FormData(f),num=k=>Number(d.get(k));S.updateExercise(d.get('day'),d.get('id'),{nameFa:String(d.get('nameFa')),nameEn:String(d.get('nameEn')),muscleGroup:String(d.get('muscleGroup')),equipment:String(d.get('equipment')),sets:num('sets'),repMin:num('repMin'),repMax:num('repMax'),restSec:num('restSec'),rirMin:num('rirMin'),rirMax:num('rirMax'),instructions:String(d.get('instructions'))});closeModal();toast('حرکت به‌روز شد.')}if(f.id==='cardioEditForm'){e.preventDefault();const d=new FormData(f),num=k=>Number(d.get(k));S.updateCardio(d.get('day'),{type:String(d.get('type')),durationMin:num('durationMin'),durationMax:num('durationMax'),intensity:String(d.get('intensity')),stepTargetMin:num('stepTargetMin'),stepTargetMax:num('stepTargetMax'),description:String(d.get('description'))});closeModal();toast('هوازی به‌روز شد.')}})

  document.addEventListener('change',async e=>{const t=e.target,a=t.dataset.action;if(a==='quick-steps')S.setSteps(t.value);if(a==='food-grams')S.updateFoodGrams(t.dataset.meal,t.dataset.food,t.value);if(a==='set-log')S.updateSetLog(t.dataset.day,t.dataset.ex,Number(t.dataset.index),{[t.dataset.field]:t.value===''?null:Number(t.value)});if(a==='profile-number')S.updateProfile({[t.dataset.key]:Number(t.value)});if(a==='theme-select')S.setTheme(t.value);if(t.id==='importFile'&&t.files?.[0]){const r=await S.import(t.files[0]);toast(r.message);t.value=''}})
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='toggle-edit')S.setEdit(!S.get().editMode);if(a==='toggle-theme')S.setTheme(S.get().theme==='dark'?'light':'dark');if(a==='water-add')S.setWater(S.get().daily.waterMl+Number(b.dataset.value));if(a==='meal-done')S.toggleMeal(b.dataset.id);if(a==='supp-done')S.toggleSupplement(b.dataset.id);if(a==='olive-mode')S.setOliveOilMode(Number(b.dataset.value));if(a==='add-food')S.addFood(b.dataset.meal);if(a==='duplicate-food')S.duplicateFood(b.dataset.meal,b.dataset.food);if(a==='remove-food'&&confirm('این خوراکی حذف شود؟'))S.removeFood(b.dataset.meal,b.dataset.food);if(a==='edit-food')editFoodModal(b.dataset.meal,b.dataset.food);if(a==='edit-supp')editSuppModal(b.dataset.id);if(a==='edit-exercise')editExerciseModal(b.dataset.day,b.dataset.ex);if(a==='remove-exercise'&&confirm('این حرکت حذف شود؟'))S.removeExercise(b.dataset.day,b.dataset.ex);if(a==='add-exercise')S.addExercise(b.dataset.day);if(a==='edit-cardio')editCardioModal(b.dataset.day);if(a==='set-done'){const st=S.get(),logs=st.daily.workoutLogs?.[b.dataset.day]?.[b.dataset.ex]||[],i=Number(b.dataset.index),cur=logs[i]||{};S.updateSetLog(b.dataset.day,b.dataset.ex,i,{done:!cur.done});if(!cur.done)startTimer(Number(b.dataset.rest)||90)}if(a==='finish-workout'){S.finishWorkout(b.dataset.day);toast('جلسه تمرینی ثبت شد.')}if(a==='remove-weight'&&confirm('این ثبت وزن حذف شود؟'))S.removeWeight(b.dataset.id);if(a==='export')S.export();if(a==='import')$('#importFile')?.click();if(a==='print')window.print();if(a==='reset'){modal('بازگشت به برنامه اصلی','<p>تمام تغییرات، لاگ‌های روز جاری و تنظیمات محلی بازنشانی می‌شوند. قبل از ادامه می‌توانی فایل پشتیبان بگیری.</p>',`<button class="btn danger" data-action="reset-confirm">بله، بازنشانی کن</button><button class="btn" data-action="close-modal">انصراف</button>`)}if(a==='reset-confirm'){S.reset();closeModal();toast('برنامه بازنشانی شد.')}if(a==='close-modal')closeModal();if(a==='modal-backdrop'&&e.target===b)closeModal();if(a==='timer-toggle'){timerState.running=!timerState.running;drawTimer()}if(a==='timer-add'){timerState.seconds+=30;drawTimer()}if(a==='timer-close')stopTimer();if(a==='install'){if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else toast('در Safari/Chrome از Add to Home Screen یا Install App استفاده کن.')}})

  window.addEventListener('hashchange',render);S.subscribe(()=>render());
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const r=$('#installRoot');if(r)r.innerHTML=`<div class="install-banner show"><span class="stat-icon">${I('download',18)}</span><div class="copy"><b>نصب FitnessCut</b><small>اپ را روی Home Screen نصب کن.</small></div><button class="btn sm primary" data-action="install">نصب</button></div>`});
  window.addEventListener('appinstalled',()=>{$('#installRoot').innerHTML='';deferredPrompt=null});
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
  if(!location.hash)location.hash='#/';render();
})();
