(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(Number(n)||0);
const round=(n,d=0)=>Number(Number(n).toFixed(d));
const uid=(p='id')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const dateKey=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const faDate=(d=new Date())=>new Intl.DateTimeFormat('fa-IR',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(d);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

const workouts={
 push:{fa:'پوش',title:'PUSH',subtitle:'سینه • سرشانه • پشت بازو',exercises:[
  ['incline-db','پرس بالا سینه دمبل','Incline Dumbbell Press',3,6,10,165],['machine-chest','پرس سینه دستگاه','Machine Chest Press',3,8,12,150],['cable-fly','فلای سیم‌کش','Cable Fly',2,10,15,90],['lateral','نشر جانب سیم‌کش/دستگاه','Cable / Machine Lateral Raise',4,10,20,75],['oh-triceps','پشت بازو بالای سر سیم‌کش','Overhead Cable Triceps Extension',3,8,12,90],['pushdown','پشت بازو سیم‌کش','Cable Triceps Pushdown',3,10,15,75]
 ]},
 pull:{fa:'پول',title:'PULL',subtitle:'زیر بغل • پشت • جلو بازو',exercises:[
  ['lat-pd','لت پول‌داون دست خنثی','Neutral Grip Lat Pulldown',3,6,10,150],['chest-row','قایقی سینه تکیه‌دار','Chest Supported Row',3,8,12,150],['one-lat','لت تک‌دست سیم‌کش','Single Arm Lat Pulldown',2,10,15,90],['cable-row','قایقی سیم‌کش','Seated Cable Row',2,8,12,120],['reverse-pec','فلای معکوس دستگاه','Reverse Pec Deck',3,12,20,75],['incline-curl','جلو بازو دمبل روی میز شیب‌دار','Incline Dumbbell Curl',3,8,12,90],['preacher','جلو بازو لاری','Preacher Curl',2,10,15,75]
 ]},
 legs:{fa:'پا',title:'LEGS',subtitle:'چهارسر • همسترینگ • باسن • ساق • شکم',exercises:[
  ['hack','هاک اسکوات','Hack Squat',3,6,10,180],['rdl','ددلیفت رومانیایی','Romanian Deadlift',3,6,10,180],['leg-press','پرس پا','Leg Press',2,10,15,150],['leg-curl','پشت پا دستگاه','Seated / Lying Leg Curl',3,8,12,105],['leg-ext','جلو پا دستگاه','Leg Extension',2,12,15,90],['calf','ساق پا','Calf Raise',3,8,15,90],['crunch','کرانچ سیم‌کش','Cable Crunch',2,10,15,75]
 ]}
};
const foodBase=[
 {id:'egg',fa:'تخم مرغ کامل',unit:'عدد',per:1,g:50,kcal:72,p:6.3,c:.4,f:4.8},{id:'oats',fa:'جو دوسر',unit:'گرم',per:40,g:40,kcal:152,p:5.2,c:27,f:3},{id:'milk',fa:'شیر کم‌چرب',unit:'لیوان',per:1,g:250,kcal:110,p:8,c:12,f:3},{id:'apple',fa:'سیب سبز',unit:'عدد متوسط',per:1,g:150,kcal:78,p:.4,c:21,f:.2},{id:'whey',fa:'پروتئین وی',unit:'اسکوپ',per:1,g:30,kcal:120,p:24,c:3,f:2},{id:'ricecake',fa:'رایس کیک',unit:'عدد',per:2,g:18,kcal:70,p:1.4,c:15,f:.5},{id:'banana',fa:'موز',unit:'عدد متوسط',per:1,g:120,kcal:105,p:1.3,c:27,f:.4},{id:'chicken',fa:'سینه مرغ پخته',unit:'گرم پخته',per:180,g:180,kcal:297,p:55.8,c:0,f:6.5},{id:'rice',fa:'برنج پخته',unit:'گرم پخته',per:150,g:150,kcal:195,p:4,c:42,f:.5},{id:'salad',fa:'سالاد و سبزیجات',unit:'گرم',per:300,g:300,kcal:90,p:4,c:18,f:1},{id:'olive',fa:'روغن زیتون',unit:'گرم',per:10,g:10,kcal:90,p:0,c:0,f:10},{id:'yogurt',fa:'ماست کم‌چرب/یونانی',unit:'گرم',per:200,g:200,kcal:130,p:14,c:10,f:3},{id:'toast',fa:'نان تست پروتئینی',unit:'عدد',per:2,g:60,kcal:150,p:8,c:25,f:2.5},{id:'pasta',fa:'پاستا پخته',unit:'گرم پخته',per:100,g:100,kcal:155,p:5.8,c:30.9,f:.9},{id:'tuna',fa:'تن ماهی آبکش‌شده',unit:'گرم',per:100,g:100,kcal:132,p:29,c:0,f:1},{id:'veg',fa:'سبزیجات',unit:'گرم',per:250,g:250,kcal:75,p:3,c:15,f:.8}
];
const mealSeed=[
 {id:'breakfast',name:'صبحانه',foods:[['egg',2],['oats',1],['milk',1],['apple',1]]},
 {id:'pre',name:'قبل از تمرین',foods:[['whey',1],['ricecake',1],['banana',1]]},
 {id:'lunch',name:'ناهار',foods:[['chicken',1],['rice',1],['salad',1],['olive',1]]},
 {id:'snack',name:'میان‌وعده',foods:[['yogurt',1],['toast',1]]},
 {id:'dinner',name:'شام',foods:[['pasta',1],['tuna',1],['veg',1],['olive',1]]}
];
function calcBMR(p){const base=10*p.weight+6.25*p.height-5*p.age;return p.sex==='female'?base-161:base+5}
function factor(a){return ({sedentary:1.2,light:1.375,moderate:1.5,high:1.725,veryHigh:1.9})[a]||1.5}
function calcPlan(p){const bmr=calcBMR(p),tdee=bmr*factor(p.activity),deficit=Math.min(500,Math.max(300,tdee*.19)),cut=Math.round((tdee-deficit)/25)*25,protein=Math.round((p.weight*2.2)/5)*5,fat=Math.max(50,Math.round((p.weight*.75)/5)*5),carbs=Math.max(100,Math.round((cut-protein*4-fat*9)/4));return{bmr:Math.round(bmr),tdee:Math.round(tdee),cut,protein,fat,carbs,deficit:Math.round(tdee-cut)}}
function seedState(){const now=new Date(),weights=[];[80,79.8,79.7,79.9,79.5,79.4,79.3].forEach((w,i)=>{const d=new Date(now);d.setDate(now.getDate()-(6-i));weights.push({date:dateKey(d),weight:w})});return{
 version:1,route:'dashboard',profile:{age:22,height:173,weight:80,target:68,sex:'male',activity:'moderate',stepsGoal:10000,waterGoal:3000,schedule:{push:'شنبه',pull:'دوشنبه',legs:'چهارشنبه'}},
 weights,measurements:[],workoutHistory:[],todayWorkout:null,mealChecks:{},supplements:{creatine:false,whey:false,bcaa:false,glutamine:false},water:1750,steps:8450,sleep:7.3,adherence:90,customFoods:[],weeklyNotes:[]};}
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem('fitnesscut_static_v1'));return x&&x.version?x:seedState()}catch{return seedState()}}
function save(){localStorage.setItem('fitnesscut_static_v1',JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function pct(a,b){return clamp((a/b)*100,0,100)}
function avg(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
function weightStats(){const xs=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date));const last7=xs.slice(-7).map(x=>x.weight),prev=xs.slice(-14,-7).map(x=>x.weight),cur=avg(last7)||state.profile.weight,prevAvg=avg(prev)||cur;return{cur:round(cur,2),prev:round(prevAvg,2),change:round(cur-prevAvg,2),latest:xs.length?xs[xs.length-1].weight:state.profile.weight}}
function mealStats(){let kcal=0,p=0,c=0,f=0;mealSeed.forEach(m=>m.foods.forEach(([id,q])=>{const x=foodBase.find(z=>z.id===id);kcal+=x.kcal*q;p+=x.p*q;c+=x.c*q;f+=x.f*q}));return{kcal:Math.round(kcal),p:Math.round(p),c:Math.round(c),f:Math.round(f)}}
function eatenStats(){let kcal=0,p=0,c=0,f=0;mealSeed.forEach(m=>{if(!state.mealChecks[`${dateKey()}_${m.id}`])return;m.foods.forEach(([id,q])=>{const x=foodBase.find(z=>z.id===id);kcal+=x.kcal*q;p+=x.p*q;c+=x.c*q;f+=x.f*q})});return{kcal:Math.round(kcal),p:Math.round(p),c:Math.round(c),f:Math.round(f)}}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}

const routes=[['dashboard','خانه','⌂'],['workout','تمرین','◉'],['nutrition','تغذیه','◒'],['progress','پیشرفت','↗'],['settings','پروفایل','◎']];
function renderNav(){const nav=routes.map(([id,label,icon])=>`<button class="nav-item ${state.route===id?'active':''}" data-route="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('');$('#desktopNav').innerHTML=nav;$('#bottomNav').innerHTML=routes.map(([id,label,icon])=>`<button class="${state.route===id?'active':''}" data-route="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}
function header(title,sub,actions=''){return `<div class="page-header"><div><h1>${title}</h1><p>${sub||''}</p></div><div class="header-actions">${actions}</div></div>`}
function metric(label,value,sub,icon='•'){return `<section class="card metric-card"><div class="metric-top"><span class="metric-label">${label}</span><span class="icon-chip">${icon}</span></div><div class="metric-value">${value}</div><div class="metric-sub">${sub||''}</div></section>`}
function macro(name,val,target){return `<div class="macro-row"><strong>${name}</strong><div class="progress-track"><div class="progress-fill" style="width:${pct(val,target)}%"></div></div><span>${fmt(val)} / ${fmt(target)}</span></div>`}
function mealTotals(m){let r={kcal:0,p:0,c:0,f:0};m.foods.forEach(([id,q])=>{const x=foodBase.find(z=>z.id===id);['kcal','p','c','f'].forEach(k=>r[k]+=x[k]*q)});return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,Math.round(v)]))}
function weightChart(){const xs=[...state.weights].sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);if(xs.length<2)return '<div class="muted small">برای نمودار حداقل دو وزن ثبت کن.</div>';const w=720,h=210,pad=26,vals=xs.map(x=>x.weight),min=Math.min(...vals,state.profile.target)-.5,max=Math.max(...vals)+.5;const x=i=>pad+i*((w-pad*2)/(xs.length-1));const y=v=>pad+(max-v)*((h-pad*2)/(max-min));const pts=xs.map((e,i)=>`${x(i)},${y(e.weight)}`).join(' ');const goalY=y(state.profile.target);let avgs=[];for(let i=0;i<xs.length;i++){const s=xs.slice(Math.max(0,i-6),i+1);avgs.push({i,v:avg(s.map(z=>z.weight))})}const avgpts=avgs.map(a=>`${x(a.i)},${y(a.v)}`).join(' ');return `<svg class="chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line x1="${pad}" x2="${w-pad}" y1="${goalY}" y2="${goalY}" class="chart-goal"/><polyline points="${pts}" class="chart-line"/><polyline points="${avgpts}" class="chart-average"/><text x="${w-100}" y="${goalY-6}" class="chart-label">هدف ${fmt(state.profile.target)} kg</text></svg>`}
function recommend(){const ws=weightStats(),weeklyRate=Math.abs(ws.change),goalLow=state.profile.weight*.005,goalHigh=state.profile.weight*.0075;if(!ws.prev||state.weights.length<8)return 'برای تصمیم هفتگی، حداقل دو هفته وزن روزانه ثبت کن.';if(state.adherence<80)return 'قبل از کاهش کالری، رعایت رژیم را به بالای ۸۰–۹۰٪ برسان و روند را دوباره بررسی کن.';if(ws.change<=-goalLow&&ws.change>=-goalHigh)return `میانگین وزن در محدوده هدف کم شده است (${fmt(Math.abs(ws.change))} kg). فعلاً کالری را تغییر نده.`;if(ws.change>-0.15)return 'روند وزن کند یا ثابت است. اگر این وضعیت دو هفته ادامه داشت و رعایت رژیم بالا بود، ۱۰۰–۱۵۰ kcal کاهش یا افزایش جزئی قدم‌ها را بررسی کن.';if(ws.change<-state.profile.weight*.01)return 'سرعت کاهش وزن بالاست. اگر عملکرد و ریکاوری افت کرده، افزایش ۱۰۰–۱۵۰ kcal را بررسی کن.';return 'روند فعلی را یک هفته دیگر با همین کالری، قدم‌ها و پروتئین ادامه بده.'}

function dashboard(){const p=calcPlan(state.profile),w=weightStats(),goalProgress=pct(state.profile.weight-w.latest,state.profile.weight-state.profile.target),e=eatenStats();return `${header('پیشرفت امروز','نمای کلی کات، تمرین، تغذیه و ریکاوری')}
<div class="grid grid-5">${metric('وزن فعلی',`${fmt(w.latest)} kg`,`هدف ${fmt(state.profile.target)} kg`,'⚖')}${metric('کالری امروز',`${fmt(p.cut)} kcal`,`کسری تخمینی ${fmt(p.deficit)} kcal`,'◔')}${metric('پروتئین',`${fmt(p.protein)} g`,`هدف روزانه`,'P')}${metric('قدم',fmt(state.steps),`از ${fmt(state.profile.stepsGoal)}`,'↟')}${metric('آب',`${fmt(state.water/1000)} L`,`از ${fmt(state.profile.waterGoal/1000)} L`,'💧')}</div>
<div class="grid dashboard-main"><div class="stack">
<section class="card workout-hero"><span class="badge green">تمرین بعدی</span><div class="workout-title">PUSH</div><div class="muted">سینه • سرشانه • پشت بازو</div><div class="small" style="margin-top:8px">۱۸ ست کاری • حدود ۶۵–۷۵ دقیقه</div><div class="workout-actions"><button class="btn btn-primary" data-start-workout="push">شروع تمرین</button><button class="btn btn-secondary" data-route="workout">مشاهده برنامه</button></div></section>
<section class="card"><div class="section-title"><h2>کالری و ماکروها</h2><span class="badge green">Training Day</span></div>${macro('کالری',e.kcal,p.cut)}${macro('پروتئین',e.p,p.protein)}${macro('کربوهیدرات',e.c,p.carbs)}${macro('چربی',e.f,p.fat)}</section>
<section class="card"><div class="section-title"><h2>روند وزن</h2><span class="badge">میانگین ۷ روزه ${fmt(w.cur)}</span></div>${weightChart()}</section>
</div><aside class="stack">
<section class="card"><div class="section-title"><h3>پیشرفت کات</h3><span class="badge green">${fmt(goalProgress)}٪</span></div><div class="big-progress"><div><div class="goal-value">${fmt(w.latest)} → ${fmt(state.profile.target)}</div><div class="muted small">${fmt(Math.max(0,w.latest-state.profile.target))} کیلو باقی مانده</div></div></div><div class="progress-track" style="margin-top:14px"><div class="progress-fill" style="width:${goalProgress}%"></div></div></section>
<section class="card"><div class="section-title"><h3>وعده‌های امروز</h3><button class="btn btn-secondary" data-route="nutrition">جزئیات</button></div>${mealSeed.map(m=>`<label class="check-row"><input type="checkbox" data-meal-check="${m.id}" ${state.mealChecks[`${dateKey()}_${m.id}`]?'checked':''}><span class="grow"><strong>${m.name}</strong><span>${mealTotals(m).kcal} kcal</span></span></label>`).join('')}</section>
<section class="card"><div class="section-title"><h3>مکمل‌های امروز</h3></div>${[['creatine','کراتین','5 g'],['whey','Whey','در صورت نیاز'],['bcaa','BCAA','اختیاری'],['glutamine','Glutamine','اختیاری']].map(x=>`<label class="check-row"><input type="checkbox" data-supp="${x[0]}" ${state.supplements[x[0]]?'checked':''}><span class="grow"><strong>${x[1]}</strong><span>${x[2]}</span></span></label>`).join('')}</section>
<section class="card"><div class="section-title"><h3>بینش هفتگی</h3></div><div class="insight">${recommend()}</div></section>
</aside></div>`}
function workoutPage(){return `${header('برنامه تمرینی','Push • Pull • Legs — سه جلسه در هفته')}
<div class="grid grid-3">${Object.entries(workouts).map(([k,d])=>`<section class="card"><div class="section-title"><div><span class="badge green">${state.profile.schedule[k]}</span><div class="day-code">${d.title}</div><div class="small muted">${d.subtitle}</div></div><span class="icon-chip">🏋️</span></div>${d.exercises.map((e,i)=>`<div class="exercise-row"><div class="exercise-order">${i+1}</div><div><h4>${e[1]}</h4><p>${e[2]}</p></div><div class="exercise-target"><strong>${e[3]} × ${e[4]}–${e[5]}</strong><div class="muted">RIR 1–2</div></div></div>`).join('')}<div class="workout-actions"><button class="btn btn-primary btn-block" data-start-workout="${k}">شروع ${d.fa}</button></div></section>`).join('')}</div>
<section class="card" style="margin-top:15px"><div class="section-title"><h2>تاریخچه تمرین</h2><span class="badge">${state.workoutHistory.length} جلسه</span></div>${state.workoutHistory.length?state.workoutHistory.slice().reverse().slice(0,8).map(x=>`<div class="list-card"><span class="icon-chip">✓</span><div class="grow"><h4>${workouts[x.day].title} — ${x.date}</h4><p>${x.totalSets} ست • ${x.duration} دقیقه</p></div><span class="badge green">ذخیره شده</span></div>`).join(''):'<div class="muted small">هنوز جلسه‌ای ثبت نشده است.</div>'}</section>`}
function nutritionPage(){const p=calcPlan(state.profile),e=eatenStats(),total=mealStats();return `${header('تغذیه','برنامه غذایی قابل اجرا با مواد غذایی در دسترس ایران',`<span class="badge green">هدف ${fmt(p.cut)} kcal</span>`)}
<div class="grid grid-4">${metric('مصرف‌شده',`${fmt(e.kcal)} kcal`,`از ${fmt(p.cut)}`,'◔')}${metric('پروتئین',`${fmt(e.p)} g`,`از ${fmt(p.protein)}`,'P')}${metric('کربوهیدرات',`${fmt(e.c)} g`,`از ${fmt(p.carbs)}`,'C')}${metric('چربی',`${fmt(e.f)} g`,`از ${fmt(p.fat)}`,'F')}</div>
<div class="grid dashboard-main"><div class="stack"><section class="card"><div class="section-title"><h2>برنامه امروز</h2><span class="badge">وزن غذاها طبق توضیح خام/پخته</span></div>${mealSeed.map(m=>{const t=mealTotals(m),checked=state.mealChecks[`${dateKey()}_${m.id}`];return `<article class="meal"><div class="meal-head"><div><h3>${m.name}</h3><span class="tiny muted">${checked?'مصرف شده':'در انتظار'}</span></div><label><input type="checkbox" data-meal-check="${m.id}" ${checked?'checked':''}> انجام شد</label></div><ul class="meal-items">${m.foods.map(([id,q])=>{const x=foodBase.find(z=>z.id===id);const amount=x.unit==='گرم'||x.unit.includes('پخته')?`${x.g*q} ${x.unit}`:`${x.per*q} ${x.unit} • حدود ${x.g*q} گرم`;return `<li>${x.fa}: ${amount}</li>`}).join('')}</ul><div class="meal-macros"><span class="badge">${t.kcal} kcal</span><span class="badge">P ${t.p} g</span><span class="badge">C ${t.c} g</span><span class="badge">F ${t.f} g</span></div></article>`}).join('')}</section></div>
<aside class="stack"><section class="card"><div class="section-title"><h3>جمع برنامه پایه</h3></div><div class="kv"><span>کالری</span><strong>${total.kcal}</strong></div><div class="kv"><span>پروتئین</span><strong>${total.p} g</strong></div><div class="kv"><span>کربوهیدرات</span><strong>${total.c} g</strong></div><div class="kv"><span>چربی</span><strong>${total.f} g</strong></div></section><section class="card"><div class="section-title"><h3>جایگزینی هوشمند</h3></div><p class="small muted">مرغ ↔ ماهی ↔ گوشت کم‌چرب ↔ تن ماهی. برنج ↔ سیب‌زمینی ↔ پاستا ↔ نان. مقدار جایگزین باید با کالری و ماکرو نزدیک تنظیم شود.</p></section><section class="card"><h3>یادآوری</h3><p class="small muted">اعداد مواد غذایی تقریبی‌اند و برچسب محصول واقعی در اولویت است. هدف اصلی رعایت مجموع کالری و پروتئین روزانه است.</p></section></aside></div>`}
function progressPage(){const w=weightStats();return `${header('پیشرفت','وزن، میانگین هفتگی، اندازه‌ها و تصمیم هفتگی',`<button class="btn btn-primary" data-modal="weight">ثبت وزن</button>`)}
<div class="grid grid-4">${metric('آخرین وزن',`${fmt(w.latest)} kg`,`ثبت‌شده`,'⚖')}${metric('میانگین ۷ روزه',`${fmt(w.cur)} kg`,`روند اصلی تصمیم‌گیری`,'≈')}${metric('تغییر هفتگی',`${w.change>0?'+':''}${fmt(w.change)} kg`,`میانگین در برابر هفته قبل`,'↗')}${metric('باقی‌مانده',`${fmt(Math.max(0,w.latest-state.profile.target))} kg`,`تا ${fmt(state.profile.target)} kg`,'◎')}</div>
<div class="grid dashboard-main"><div class="stack"><section class="card"><div class="section-title"><h2>نمودار وزن</h2><span class="badge">روزانه + میانگین</span></div>${weightChart()}</section><section class="card"><div class="section-title"><h2>ثبت‌های اخیر</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>تاریخ</th><th>وزن</th></tr></thead><tbody>${[...state.weights].reverse().slice(0,12).map(x=>`<tr><td>${x.date}</td><td>${fmt(x.weight)} kg</td></tr>`).join('')}</tbody></table></div></section></div>
<aside class="stack"><section class="card"><div class="section-title"><h3>Weekly Check-in</h3></div><div class="field"><label>رعایت رژیم</label><input id="adherenceRange" type="range" min="0" max="100" step="5" value="${state.adherence}"><div class="small">${fmt(state.adherence)}٪</div></div><div class="field" style="margin-top:12px"><label>خواب متوسط</label><input id="sleepInput" class="input" type="number" step="0.1" value="${state.sleep}"></div><button class="btn btn-primary btn-block" id="saveCheckin" style="margin-top:12px">ذخیره Check-in</button></section><section class="card"><h3>تصمیم پیشنهادی</h3><div class="insight">${recommend()}</div></section><section class="card"><div class="section-title"><h3>اندازه‌ها</h3><button class="btn btn-secondary" data-modal="measure">ثبت</button></div>${state.measurements.length?state.measurements.slice().reverse().slice(0,5).map(x=>`<div class="kv"><span>${x.date}</span><strong>کمر ${fmt(x.waist)} cm</strong></div>`).join(''):'<div class="muted small">هنوز اندازه‌ای ثبت نشده است.</div>'}</section></aside></div>`}
function settingsPage(){const p=state.profile,plan=calcPlan(p);return `${header('پروفایل و تنظیمات','تمام اعداد اصلی با تغییر مشخصات دوباره محاسبه می‌شوند',`<button id="exportBtn" class="btn btn-secondary">خروجی JSON</button>`)}
<div class="grid dashboard-main"><div class="stack"><section class="card"><div class="section-title"><h2>مشخصات</h2><span class="badge green">Dynamic</span></div><form id="settingsForm" class="form-grid">
<div class="field"><label>سن</label><input class="input" name="age" type="number" min="16" max="80" value="${p.age}"></div><div class="field"><label>جنسیت برای فرمول BMR</label><select class="select" name="sex"><option value="male" ${p.sex==='male'?'selected':''}>مرد</option><option value="female" ${p.sex==='female'?'selected':''}>زن</option></select></div>
<div class="field"><label>قد (cm)</label><input class="input" name="height" type="number" value="${p.height}"></div><div class="field"><label>وزن مبنا (kg)</label><input class="input" name="weight" type="number" step="0.1" value="${p.weight}"></div><div class="field"><label>وزن هدف (kg)</label><input class="input" name="target" type="number" step="0.1" value="${p.target}"></div><div class="field"><label>سطح فعالیت</label><select class="select" name="activity"><option value="sedentary" ${p.activity==='sedentary'?'selected':''}>کم‌تحرک</option><option value="light" ${p.activity==='light'?'selected':''}>سبک</option><option value="moderate" ${p.activity==='moderate'?'selected':''}>متوسط</option><option value="high" ${p.activity==='high'?'selected':''}>زیاد</option><option value="veryHigh" ${p.activity==='veryHigh'?'selected':''}>خیلی زیاد</option></select></div><div class="field"><label>هدف قدم</label><input class="input" name="stepsGoal" type="number" step="500" value="${p.stepsGoal}"></div><div class="field"><label>هدف آب (ml)</label><input class="input" name="waterGoal" type="number" step="250" value="${p.waterGoal}"></div><div style="grid-column:1/-1"><button class="btn btn-primary">ذخیره و محاسبه مجدد</button></div></form></section>
<section class="card"><div class="section-title"><h2>محاسبات فعلی</h2><span class="badge amber">تخمینی</span></div><div class="summary-list"><div class="summary-item"><strong>${fmt(plan.bmr)}</strong><span>BMR kcal</span></div><div class="summary-item"><strong>${fmt(plan.tdee)}</strong><span>TDEE kcal</span></div><div class="summary-item"><strong>${fmt(plan.cut)}</strong><span>Cut kcal</span></div><div class="summary-item"><strong>${fmt(plan.protein)} g</strong><span>Protein</span></div><div class="summary-item"><strong>${fmt(plan.carbs)} g</strong><span>Carbs</span></div><div class="summary-item"><strong>${fmt(plan.fat)} g</strong><span>Fat</span></div></div></section></div>
<aside class="stack"><section class="card"><div class="section-title"><h3>نصب روی آیفون</h3><span class="badge green">PWA</span></div><ol class="install-steps"><li>اپ را از یک آدرس HTTPS در Safari باز کن.</li><li>Share را بزن.</li><li>Add to Home Screen را انتخاب کن.</li><li>از آیکون Home Screen اجرا کن.</li></ol><button class="btn btn-primary btn-block" id="installGuide" style="margin-top:12px">راهنمای نصب</button></section><section class="card"><h3>ذخیره‌سازی</h3><p class="small muted">این نسخه Local-first است و داده‌ها در مرورگر همین دستگاه ذخیره می‌شوند. برای جابه‌جایی دستگاه از خروجی JSON استفاده کن.</p></section><section class="card danger-zone"><h3>ریست داده‌ها</h3><p class="small muted">تمام ثبت‌های محلی حذف و داده نمونه اولیه بازگردانده می‌شود.</p><button class="btn btn-danger" id="resetBtn">بازنشانی کامل</button></section></aside></div>`}
function liveWorkout(day){const d=workouts[day],draft=state.todayWorkout&&state.todayWorkout.day===day?state.todayWorkout:{day,started:Date.now(),exerciseIndex:0,records:{}};state.todayWorkout=draft;save();const ei=draft.exerciseIndex,e=d.exercises[ei],saved=draft.records[e[0]]||[],setNo=saved.length+1,done=saved.length>=e[3],prev=findPrevious(day,e[0]);return `${header(`جلسه ${d.title}`,`${d.subtitle} • حرکت ${ei+1} از ${d.exercises.length}`,`<button class="btn btn-secondary" data-route="workout">خروج</button>`)}
<div class="grid dashboard-main"><div class="stack"><section class="card"><div class="section-title"><div><span class="badge green">${e[1]}</span><h2 style="margin:7px 0 0">${e[2]}</h2></div><div class="exercise-target"><strong>${e[3]} × ${e[4]}–${e[5]}</strong><div class="muted">RIR 1–2</div></div></div>${prev?`<div class="callout">جلسه قبل: ${prev.map(s=>`${s.weight}×${s.reps}`).join(' • ')}</div>`:''}<div style="margin-top:15px"><div class="set-grid"><div>ست</div><div class="tiny muted">وزنه</div><div class="tiny muted">تکرار</div><div class="tiny muted">RIR</div><div></div></div>${Array.from({length:e[3]},(_,i)=>{const s=saved[i];if(s)return `<div class="set-grid"><div>${i+1}</div><div class="input">${s.weight}</div><div class="input">${s.reps}</div><div class="input">${s.rir}</div><span class="badge green">ثبت شد</span></div>`;if(i===setNo-1&&!done)return `<div class="set-grid"><div>${i+1}</div><input id="setWeight" class="input" type="number" step="0.5" inputmode="decimal" value="${prev?.[i]?.weight||0}"><input id="setReps" class="input" type="number" inputmode="numeric" value="${prev?.[i]?.reps||e[4]}"><input id="setRir" class="input" type="number" min="0" max="5" inputmode="numeric" value="2"><button class="btn btn-primary" data-save-set>ثبت</button></div>`;return `<div class="set-grid"><div>${i+1}</div><div class="input">—</div><div class="input">—</div><div class="input">—</div><div></div></div>`}).join('')}</div><div id="timerArea"></div></section><section class="card"><h3>راهنما</h3><p class="small muted">دامنه کامل و کنترل‌شده، فرم ثابت، و بیشتر ست‌های کاری با ۱–۲ تکرار ذخیره (RIR). استراحت هدف این حرکت ${e[6]} ثانیه است.</p></section></div><aside class="stack"><section class="card"><h3>پیشرفت جلسه</h3><div class="progress-track"><div class="progress-fill" style="width:${workoutCompletion(draft,d)}%"></div></div><div class="small muted" style="margin-top:8px">${countSets(draft)} ست ثبت شده</div></section><section class="card"><h3>Double Progression</h3><p class="small muted">اگر همه ست‌ها به سقف بازه تکرار رسیدند و RIR هدف حفظ شد، جلسه بعد افزایش کوچک وزنه منطقی است.</p></section></aside></div><div class="sticky-workout">${done?(ei<d.exercises.length-1?`<button class="btn btn-primary btn-block" data-next-exercise>حرکت بعدی</button>`:`<button class="btn btn-primary btn-block" data-finish-workout>پایان و ذخیره تمرین</button>`):`<div class="small muted" style="text-align:center">ست بعدی را ثبت کن</div>`}</div>`}
function countSets(d){return Object.values(d.records).reduce((a,b)=>a+b.length,0)}
function workoutCompletion(d,meta){return Math.round(countSets(d)/meta.exercises.reduce((a,e)=>a+e[3],0)*100)}
function findPrevious(day,id){for(let i=state.workoutHistory.length-1;i>=0;i--){const w=state.workoutHistory[i];if(w.day===day&&w.records[id])return w.records[id]}return null}
let timerId=null;
function startTimer(sec){clearInterval(timerId);let remaining=sec;const draw=()=>{const area=$('#timerArea');if(!area)return;area.innerHTML=`<div class="rest-timer" style="margin-top:14px"><div><span class="tiny">استراحت</span><strong>${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}</strong></div><button class="btn btn-secondary" data-skip-timer>رد کردن</button></div>`};draw();timerId=setInterval(()=>{remaining--;draw();if(remaining<=0){clearInterval(timerId);navigator.vibrate?.(180);toast('استراحت تمام شد')}} ,1000)}
function render(){renderNav();$('#todayLabel').textContent=faDate();let html='';if(state.route==='dashboard')html=dashboard();else if(state.route==='workout')html=workoutPage();else if(state.route==='nutrition')html=nutritionPage();else if(state.route==='progress')html=progressPage();else if(state.route==='settings')html=settingsPage();else if(state.route.startsWith('live:'))html=liveWorkout(state.route.split(':')[1]);$('#content').innerHTML=html;bindPage();window.scrollTo({top:0,behavior:'instant'})}
function bindPage(){
 $$('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;save();render()});
 $$('[data-start-workout]').forEach(b=>b.onclick=()=>{state.route=`live:${b.dataset.startWorkout}`;state.todayWorkout=null;save();render()});
 $$('[data-meal-check]').forEach(c=>c.onchange=()=>{state.mealChecks[`${dateKey()}_${c.dataset.mealCheck}`]=c.checked;save();render()});
 $$('[data-supp]').forEach(c=>c.onchange=()=>{state.supplements[c.dataset.supp]=c.checked;save();render()});
 $$('[data-modal="weight"]').forEach(b=>b.onclick=()=>openWeightModal());$$('[data-modal="measure"]').forEach(b=>b.onclick=()=>openMeasureModal());
 const ad=$('#adherenceRange');if(ad)ad.oninput=()=>{state.adherence=Number(ad.value);save();render()}; const sl=$('#sleepInput');if(sl)sl.onchange=()=>{state.sleep=Number(sl.value);save()}; const sc=$('#saveCheckin');if(sc)sc.onclick=()=>{state.weeklyNotes.push({date:dateKey(),adherence:state.adherence,sleep:state.sleep,recommendation:recommend()});save();toast('Check-in ذخیره شد');render()};
 const sf=$('#settingsForm');if(sf)sf.onsubmit=e=>{e.preventDefault();const f=new FormData(sf);['age','height','weight','target','stepsGoal','waterGoal'].forEach(k=>state.profile[k]=Number(f.get(k)));state.profile.sex=f.get('sex');state.profile.activity=f.get('activity');save();toast('تنظیمات ذخیره شد');render()};
 const ex=$('#exportBtn');if(ex)ex.onclick=exportData;const rb=$('#resetBtn');if(rb)rb.onclick=()=>{if(confirm('همه داده‌های محلی پاک شوند؟')){state=seedState();save();render();toast('داده‌ها بازنشانی شد')}};const ig=$('#installGuide');if(ig)ig.onclick=showInstallGuide;
 const ss=$('[data-save-set]');if(ss)ss.onclick=()=>{const day=state.route.split(':')[1],d=workouts[day],tw=state.todayWorkout,e=d.exercises[tw.exerciseIndex],rec=tw.records[e[0]]||[];rec.push({weight:Number($('#setWeight').value)||0,reps:Number($('#setReps').value)||0,rir:clamp(Number($('#setRir').value)||0,0,5)});tw.records[e[0]]=rec;state.todayWorkout=tw;save();render();startTimer(e[6])};
 const ne=$('[data-next-exercise]');if(ne)ne.onclick=()=>{state.todayWorkout.exerciseIndex++;save();render()};const fw=$('[data-finish-workout]');if(fw)fw.onclick=()=>{const tw=state.todayWorkout;const meta=workouts[tw.day];state.workoutHistory.push({id:uid('w'),date:dateKey(),day:tw.day,duration:Math.max(1,Math.round((Date.now()-tw.started)/60000)),records:tw.records,totalSets:countSets(tw)});state.todayWorkout=null;state.route='workout';save();toast('تمرین ذخیره شد');render()};
 const sk=$('[data-skip-timer]');if(sk)sk.onclick=()=>{clearInterval(timerId);$('#timerArea').innerHTML=''};
}
function openWeightModal(){modal(`<h2>ثبت وزن امروز</h2><p class="muted small">ترجیحاً صبح، بعد از دستشویی و قبل از صبحانه.</p><div class="field"><label>وزن (kg)</label><input id="weightModalInput" class="input" type="number" step="0.1" inputmode="decimal" value="${weightStats().latest}"></div><div class="modal-actions"><button class="btn btn-primary" id="saveWeightModal">ذخیره</button><button class="btn btn-secondary" data-close-modal>انصراف</button></div>`);$('#saveWeightModal').onclick=()=>{const v=Number($('#weightModalInput').value);if(v<35||v>250)return toast('وزن واردشده معتبر نیست');const existing=state.weights.find(x=>x.date===dateKey());if(existing)existing.weight=v;else state.weights.push({date:dateKey(),weight:v});save();closeModal();render();toast('وزن ثبت شد')}}
function openMeasureModal(){modal(`<h2>ثبت اندازه‌ها</h2><div class="form-grid"><div class="field"><label>دور کمر cm</label><input id="mWaist" class="input" type="number" step="0.1"></div><div class="field"><label>دور سینه cm</label><input id="mChest" class="input" type="number" step="0.1"></div><div class="field"><label>بازو cm</label><input id="mArm" class="input" type="number" step="0.1"></div><div class="field"><label>ران cm</label><input id="mThigh" class="input" type="number" step="0.1"></div></div><div class="modal-actions"><button class="btn btn-primary" id="saveMeasure">ذخیره</button><button class="btn btn-secondary" data-close-modal>انصراف</button></div>`);$('#saveMeasure').onclick=()=>{state.measurements.push({date:dateKey(),waist:Number($('#mWaist').value)||0,chest:Number($('#mChest').value)||0,arm:Number($('#mArm').value)||0,thigh:Number($('#mThigh').value)||0});save();closeModal();render();toast('اندازه‌ها ثبت شد')}}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`;$$('[data-close-modal]').forEach(b=>b.onclick=closeModal);$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}
function closeModal(){$('#modalRoot').innerHTML=''}
function showInstallGuide(){modal(`<h2>نصب روی آیفون</h2><ol class="install-steps"><li>نسخه وب را روی یک آدرس HTTPS منتشر کن.</li><li>آن آدرس را فقط با Safari آیفون باز کن.</li><li>دکمه Share (مربع با فلش رو به بالا) را بزن.</li><li>گزینه Add to Home Screen را انتخاب کن.</li><li>Add را بزن؛ FitnessCut مثل اپ مستقل اجرا می‌شود.</li></ol><div class="callout" style="margin-top:14px">برای نصب PWA، اجرای مستقیم فایل index.html از Files کافی نیست؛ باید از HTTPS سرو شود.</div><div class="modal-actions"><button class="btn btn-primary" data-close-modal>متوجه شدم</button></div>`);$$('[data-close-modal]').forEach(b=>b.onclick=closeModal)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`fitnesscut-backup-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
let deferredPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else showInstallGuide()};
window.addEventListener('online',()=>toast('اتصال اینترنت برقرار شد'));window.addEventListener('offline',()=>toast('حالت آفلاین فعال است'));
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
})();
